// Auto-generated by Zenith CLI. Do not edit manually.
export {};

declare global {
  namespace Zenith {
    interface RouteParamsMap {
      "/": {};
    }

    type ParamsFor<P extends keyof RouteParamsMap> = RouteParamsMap[P];
  }
}

