// Auto-generated by Zenith CLI. Do not edit manually.
export {};

declare global {
  namespace Zenith {
    type Params = Record<string, string>;

    interface ErrorState {
      status?: number;
      code?: string;
      message: string;
    }

    type PageData = Record<string, unknown> & { __zenith_error?: ErrorState };

    interface RouteMeta {
      id: string;
      file: string;
      pattern: string;
    }

    interface LoadContext {
      params: Params;
      url: URL;
      request: Request;
      route: RouteMeta;
    }

    type Load<T extends PageData = PageData> = (ctx: LoadContext) => Promise<T> | T;

    interface Fragment {
      __zenith_fragment: true;
      mount: (anchor: Node | null) => void;
      unmount: () => void;
    }

    type Renderable =
      | string
      | number
      | boolean
      | null
      | undefined
      | Renderable[]
      | Fragment;
  }
}
