import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';

export async function generateEnvDts(projectRoot) {
    const content = `// .zenith/zenith-env.d.ts
// Auto-generated by Zenith. Do not edit.

export {};

declare global {
  namespace Zenith {
    type Params = Record<string, string>;

    interface LoadContext {
      params: Params;
      url: URL;
      request: Request;
      route: {
        id: string;
        file: string;
        pattern: string;
      };
    }

    interface ErrorState {
      status?: number;
      code?: string;
      message: string;
    }

    type PageData = Record<string, unknown> & {
      __zenith_error?: ErrorState;
    };

    type Load<T extends PageData = PageData> = (ctx: LoadContext) => Promise<T> | T;

    type Renderable =
      | string
      | number
      | boolean
      | null
      | undefined
      | Renderable[]
      | { __zenith_fragment: true };
  }
}
`;

    const outPath = join(projectRoot, '.zenith', 'zenith-env.d.ts');
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, content, 'utf8');
}
